"""Assemble updates/*.json into the updates.js the site loads.

Why this exists
---------------
Every change to Matchday adds a release-note entry, and that entry used to be
prepended to a single `SYSTEM_UPDATES` array literal inside app-1-core.js. Two
branches developed in parallel therefore edited the *same lines at the same
position* every single time, so every pull request conflicted with every other
one regardless of what it actually changed -- confirmed live 2026-07-30, when
two unrelated branches both prepended an entry and both claimed "Build 0730A".

One file per build removes the shared line entirely: a new entry is a new file,
which no other branch has touched. `updates.js` is generated from that
directory and is committed only so the site keeps working with a plain static
file server (no build step locally). It must never be hand-edited -- if it ever
conflicts, the resolution is to re-run this script, not to merge prose by hand.

Usage:
    python build_updates.py            # regenerate updates.js
    python build_updates.py --check    # fail if updates.js is out of sync
"""
import glob
import io
import json
import os
import sys

UPDATES_DIR = "updates"
OUTPUT = "updates.js"
REQUIRED_FIELDS = ("rank", "date", "tag", "title", "items")


def load_entries(directory=UPDATES_DIR):
    """Every entry, newest first.

    Ordered by an explicit `rank` rather than by build label: labels like
    "Build 0724O" and "Recent" don't sort consistently against each other, and
    the display order is a product decision, not something to infer from a
    filename.
    """
    entries = []
    for path in sorted(glob.glob(os.path.join(directory, "*.json"))):
        with io.open(path, encoding="utf-8") as handle:
            entry = json.load(handle)
        missing = [field for field in REQUIRED_FIELDS if field not in entry]
        if missing:
            raise ValueError("%s is missing %s" % (path, ", ".join(missing)))
        if not isinstance(entry["items"], list) or not entry["items"]:
            raise ValueError("%s must list at least one item" % path)
        entry["_path"] = path
        entries.append(entry)
    ranks = [entry["rank"] for entry in entries]
    duplicates = {rank for rank in ranks if ranks.count(rank) > 1}
    if duplicates:
        clashing = sorted(e["_path"] for e in entries if e["rank"] in duplicates)
        raise ValueError("duplicate rank(s) %s in %s" % (sorted(duplicates), clashing))
    entries.sort(key=lambda entry: -entry["rank"])
    return entries


def render(entries):
    payload = [{"date": e["date"], "tag": e["tag"], "title": e["title"], "items": e["items"]}
               for e in entries]
    body = json.dumps(payload, ensure_ascii=False, indent=1)
    return (
        "/* GENERATED by build_updates.py from updates/*.json -- do not edit.\n"
        "   Add a release note by creating updates/<build>.json, then re-run\n"
        "   `python build_updates.py`. Never resolve a conflict in this file by\n"
        "   hand; regenerate it instead. */\n"
        "window.SYSTEM_UPDATES=%s;\n" % body
    )


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    entries = load_entries()
    if not entries:
        print("no entries found in %s/" % UPDATES_DIR)
        return 1
    rendered = render(entries)
    if "--check" in argv:
        try:
            with io.open(OUTPUT, encoding="utf-8") as handle:
                current = handle.read()
        except OSError:
            current = None
        if current != rendered:
            print("%s is out of sync with %s/. Run: python build_updates.py" % (OUTPUT, UPDATES_DIR))
            return 1
        print("%s is in sync (%d entries)" % (OUTPUT, len(entries)))
        return 0
    with io.open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(rendered)
    print("wrote %s from %d entries (newest: %s)" % (OUTPUT, len(entries), entries[0]["date"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
