// Matchday Terminal — UI translations (chrome layer)
// Exact-string dictionary applied at render time. English is the source of truth;
// anything unmapped stays English. Native-speaker review welcome before public launch.
window.MD_I18N = {
es: {
"Results":"Resultados","Fixtures":"Partidos","Groups":"Grupos","Odds":"Cuotas","Model":"Modelo","Scorecard":"Historial","Bracket":"Cuadro","Thirds":"Terceros","News":"Noticias","Status":"Estado","Updates":"Novedades","Customize":"Personalizar",
"Odds board":"Panel de cuotas","Biggest movers since open":"Mayores movimientos desde la apertura","Where the books disagree":"Donde discrepan las casas","Match markets · win probability":"Mercados · probabilidad de victoria","Advancement odds · Matchday model":"Probabilidades de avance · modelo Matchday","Golden Boot race":"Carrera por la Bota de Oro","Odds to win the tournament":"Cuotas para ganar el torneo",
"Model pick":"Elección del modelo","Pick":"Elección","Market read":"Lectura del mercado","Odds tracker":"Seguimiento de cuotas","Match read":"Análisis del partido","Lineups":"Alineaciones","Markets":"Mercados","Stats":"Estadísticas","Analyst read":"Lectura del analista","Model read":"Lectura del modelo","In focus":"En foco","Latest":"Lo último",
"LIVE":"EN VIVO","UPCOMING":"PRÓXIMO","FINISHED":"FINAL","live data":"datos en vivo","live feed":"conexión activa","sample data":"datos de ejemplo","draw":"empate","Draw":"Empate",
"Model record":"Registro del modelo","Market favourite":"Favorito del mercado","When we split with the market":"Cuando discrepamos del mercado","Pending":"Pendientes","Closing line value":"Valor de línea de cierre","Brier score":"Puntuación Brier","Calibration":"Calibración","Value signals":"Señales de valor","Pick log":"Registro de elecciones",
"Through":"Clasificado","Eliminated":"Eliminado","Through as 3rd":"Clasificado como 3.º","Win to go through":"Gana y clasifica","In contention":"En la pelea","In 3rd-place race":"En la lucha de terceros",
"Substitutions":"Sustituciones","Absences":"Bajas","Head-to-head":"Cara a cara","Position":"Posición","Points":"Puntos","Goal diff":"Dif. de goles","Last 5":"Últimos 5","Team":"Equipo","Form":"Forma",
"Box-score stats appear once the match kicks off.":"Las estadísticas del partido aparecen cuando comienza el encuentro.",
"analytics only, not betting advice":"solo análisis, no es consejo de apuestas",
"Knockout bracket":"Cuadro eliminatorio","Best third-placed race · top 8 advance":"Mejores terceros · avanzan 8","Final":"Final","Semi-finals":"Semifinales","Quarter-finals":"Cuartos de final","Round of 16":"Octavos de final","Round of 32":"Dieciseisavos","Third-place playoff":"Tercer puesto","Champion":"Campeón","Win":"Título"
},
fr: {
"Results":"Résultats","Fixtures":"Matchs","Groups":"Groupes","Odds":"Cotes","Model":"Modèle","Scorecard":"Bilan","Bracket":"Tableau","Thirds":"Troisièmes","News":"Actus","Status":"État","Updates":"Mises à jour","Customize":"Personnaliser",
"Odds board":"Tableau des cotes","Biggest movers since open":"Plus fortes variations depuis l'ouverture","Where the books disagree":"Là où les bookmakers divergent","Match markets · win probability":"Marchés · probabilité de victoire","Advancement odds · Matchday model":"Probabilités de qualification · modèle Matchday","Golden Boot race":"Course au Soulier d'or","Odds to win the tournament":"Cotes pour remporter le tournoi",
"Model pick":"Choix du modèle","Pick":"Choix","Market read":"Lecture du marché","Odds tracker":"Suivi des cotes","Match read":"Analyse du match","Lineups":"Compositions","Markets":"Marchés","Stats":"Statistiques","Analyst read":"Analyse","Model read":"Lecture du modèle","In focus":"À la une","Latest":"Dernières actus",
"LIVE":"EN DIRECT","UPCOMING":"À VENIR","FINISHED":"TERMINÉ","live data":"données en direct","live feed":"flux actif","sample data":"données d'exemple","draw":"nul","Draw":"Nul",
"Model record":"Bilan du modèle","Market favourite":"Favori du marché","When we split with the market":"Quand nous divergeons du marché","Pending":"En attente","Closing line value":"Valeur de clôture","Brier score":"Score de Brier","Calibration":"Calibration","Value signals":"Signaux de valeur","Pick log":"Journal des choix",
"Through":"Qualifié","Eliminated":"Éliminé","Through as 3rd":"Qualifié comme 3e","Win to go through":"Gagner pour se qualifier","In contention":"En course","In 3rd-place race":"Dans la course des 3es",
"Substitutions":"Remplacements","Absences":"Absents","Head-to-head":"Confrontations","Position":"Position","Points":"Points","Goal diff":"Diff. de buts","Last 5":"5 derniers","Team":"Équipe","Form":"Forme",
"Box-score stats appear once the match kicks off.":"Les statistiques du match apparaissent après le coup d'envoi.",
"analytics only, not betting advice":"analyse uniquement, pas un conseil de pari",
"Knockout bracket":"Tableau final","Best third-placed race · top 8 advance":"Meilleurs troisièmes · 8 qualifiés","Final":"Finale","Semi-finals":"Demi-finales","Quarter-finals":"Quarts de finale","Round of 16":"Huitièmes de finale","Round of 32":"Seizièmes","Third-place playoff":"Petite finale","Champion":"Champion","Win":"Titre"
},
de: {
"Results":"Ergebnisse","Fixtures":"Spiele","Groups":"Gruppen","Odds":"Quoten","Model":"Modell","Scorecard":"Bilanz","Bracket":"Turnierbaum","Thirds":"Dritte","News":"News","Status":"Status","Updates":"Updates","Customize":"Anpassen",
"Odds board":"Quotenboard","Biggest movers since open":"Größte Bewegungen seit Eröffnung","Where the books disagree":"Wo die Buchmacher uneins sind","Match markets · win probability":"Spielmärkte · Siegwahrscheinlichkeit","Advancement odds · Matchday model":"Weiterkommen · Matchday-Modell","Golden Boot race":"Torjägerkanone","Odds to win the tournament":"Quoten auf den Turniersieg",
"Model pick":"Modell-Tipp","Pick":"Tipp","Market read":"Marktlage","Odds tracker":"Quoten-Tracker","Match read":"Spielanalyse","Lineups":"Aufstellungen","Markets":"Märkte","Stats":"Statistiken","Analyst read":"Analyse","Model read":"Modell-Analyse","In focus":"Im Fokus","Latest":"Aktuelles",
"LIVE":"LIVE","UPCOMING":"ANSTEHEND","FINISHED":"BEENDET","live data":"Live-Daten","live feed":"Feed aktiv","sample data":"Beispieldaten","draw":"Remis","Draw":"Remis",
"Model record":"Modell-Bilanz","Market favourite":"Marktfavorit","When we split with the market":"Wenn wir vom Markt abweichen","Pending":"Ausstehend","Closing line value":"Closing Line Value","Brier score":"Brier-Score","Calibration":"Kalibrierung","Value signals":"Value-Signale","Pick log":"Tipp-Protokoll",
"Through":"Weiter","Eliminated":"Ausgeschieden","Through as 3rd":"Als Dritter weiter","Win to go through":"Sieg zum Weiterkommen","In contention":"Im Rennen","In 3rd-place race":"Im Rennen der Dritten",
"Substitutions":"Wechsel","Absences":"Ausfälle","Head-to-head":"Direkter Vergleich","Position":"Platz","Points":"Punkte","Goal diff":"Tordifferenz","Last 5":"Letzte 5","Team":"Team","Form":"Form",
"Box-score stats appear once the match kicks off.":"Spielstatistiken erscheinen nach dem Anpfiff.",
"analytics only, not betting advice":"nur Analyse, keine Wettempfehlung",
"Knockout bracket":"K.-o.-Runde","Best third-placed race · top 8 advance":"Beste Gruppendritte · 8 kommen weiter","Final":"Finale","Semi-finals":"Halbfinale","Quarter-finals":"Viertelfinale","Round of 16":"Achtelfinale","Round of 32":"Sechzehntelfinale","Third-place playoff":"Spiel um Platz 3","Champion":"Sieger","Win":"Titel"
},
pt: {
"Results":"Resultados","Fixtures":"Jogos","Groups":"Grupos","Odds":"Odds","Model":"Modelo","Scorecard":"Histórico","Bracket":"Chaveamento","Thirds":"Terceiros","News":"Notícias","Status":"Estado","Updates":"Novidades","Customize":"Personalizar",
"Odds board":"Painel de odds","Biggest movers since open":"Maiores movimentos desde a abertura","Where the books disagree":"Onde as casas divergem","Match markets · win probability":"Mercados · probabilidade de vitória","Advancement odds · Matchday model":"Probabilidades de avanço · modelo Matchday","Golden Boot race":"Corrida pela Chuteira de Ouro","Odds to win the tournament":"Odds para vencer o torneio",
"Model pick":"Escolha do modelo","Pick":"Escolha","Market read":"Leitura do mercado","Odds tracker":"Acompanhamento de odds","Match read":"Análise da partida","Lineups":"Escalações","Markets":"Mercados","Stats":"Estatísticas","Analyst read":"Leitura do analista","Model read":"Leitura do modelo","In focus":"Em foco","Latest":"Últimas",
"LIVE":"AO VIVO","UPCOMING":"EM BREVE","FINISHED":"ENCERRADO","live data":"dados ao vivo","live feed":"conexão ativa","sample data":"dados de exemplo","draw":"empate","Draw":"Empate",
"Model record":"Registro do modelo","Market favourite":"Favorito do mercado","When we split with the market":"Quando divergimos do mercado","Pending":"Pendentes","Closing line value":"Valor da linha de fechamento","Brier score":"Pontuação Brier","Calibration":"Calibração","Value signals":"Sinais de valor","Pick log":"Registro de escolhas",
"Through":"Classificado","Eliminated":"Eliminado","Through as 3rd":"Classificado como 3º","Win to go through":"Vença para avançar","In contention":"Na disputa","In 3rd-place race":"Na disputa dos terceiros",
"Substitutions":"Substituições","Absences":"Desfalques","Head-to-head":"Confronto direto","Position":"Posição","Points":"Pontos","Goal diff":"Saldo de gols","Last 5":"Últimos 5","Team":"Equipe","Form":"Fase",
"Box-score stats appear once the match kicks off.":"As estatísticas da partida aparecem após o pontapé inicial.",
"analytics only, not betting advice":"apenas análise, não é recomendação de aposta",
"Knockout bracket":"Fase eliminatória","Best third-placed race · top 8 advance":"Melhores terceiros · 8 avançam","Final":"Final","Semi-finals":"Semifinais","Quarter-finals":"Quartas de final","Round of 16":"Oitavas de final","Round of 32":"Dezesseis avos","Third-place playoff":"Disputa de 3º lugar","Champion":"Campeão","Win":"Título"
},
ru: {
"Results":"Результаты","Fixtures":"Матчи","Groups":"Группы","Odds":"Коэффициенты","Model":"Модель","Scorecard":"Статистика","Bracket":"Сетка","Thirds":"Третьи места","News":"Новости","Status":"Статус","Updates":"Обновления","Customize":"Настройки",
"Odds board":"Панель коэффициентов","Biggest movers since open":"Наибольшие изменения с открытия","Where the books disagree":"Где букмекеры расходятся","Match markets · win probability":"Рынки · вероятность победы","Advancement odds · Matchday model":"Шансы на проход · модель Matchday","Golden Boot race":"Гонка бомбардиров","Odds to win the tournament":"Коэффициенты на победу в турнире",
"Model pick":"Выбор модели","Pick":"Выбор","Market read":"Оценка рынка","Odds tracker":"Движение коэффициентов","Match read":"Разбор матча","Lineups":"Составы","Markets":"Рынки","Stats":"Статистика","Analyst read":"Комментарий аналитика","Model read":"Оценка модели","In focus":"В центре внимания","Latest":"Последнее",
"LIVE":"LIVE","UPCOMING":"СКОРО","FINISHED":"ЗАВЕРШЁН","live data":"живые данные","live feed":"поток активен","sample data":"пример данных","draw":"ничья","Draw":"Ничья",
"Model record":"Результаты модели","Market favourite":"Фаворит рынка","When we split with the market":"Когда мы расходимся с рынком","Pending":"Ожидают","Closing line value":"Ценность закрытия линии","Brier score":"Оценка Брайера","Calibration":"Калибровка","Value signals":"Сигналы ценности","Pick log":"Журнал выборов",
"Through":"Вышел","Eliminated":"Выбыл","Through as 3rd":"Вышел с 3-го места","Win to go through":"Победа выводит дальше","In contention":"В борьбе","In 3rd-place race":"В гонке третьих мест",
"Substitutions":"Замены","Absences":"Потери","Head-to-head":"Очные встречи","Position":"Позиция","Points":"Очки","Goal diff":"Разница мячей","Last 5":"Последние 5","Team":"Команда","Form":"Форма",
"Box-score stats appear once the match kicks off.":"Статистика матча появится после стартового свистка.",
"analytics only, not betting advice":"только аналитика, не является советом по ставкам",
"Knockout bracket":"Сетка плей-офф","Best third-placed race · top 8 advance":"Лучшие третьи · проходят 8","Final":"Финал","Semi-finals":"Полуфиналы","Quarter-finals":"Четвертьфиналы","Round of 16":"1/8 финала","Round of 32":"1/16 финала","Third-place playoff":"Матч за 3-е место","Champion":"Чемпион","Win":"Титул"
}
};

// Complete chrome, onboarding and personalization copy. Provider-supplied team,
// player and article text intentionally remains in its source language.
Object.assign(window.MD_I18N.es,{
"Matches":"Partidos","Forecast":"Pronóstico","Community":"Comunidad","Team of Tournament":"Equipo del torneo","Table":"Tabla","Standings":"Clasificación","Rankings":"Ránking","Conferences":"Conferencias","My team":"Mi equipo","No favorite selected":"Sin equipo favorito","Your team moves to the front of matches, news, tables and the insight panel.":"Tu equipo aparece primero en partidos, noticias, tablas y el panel de análisis.",
"Know the match.":"Conoce el partido.","See the tension.":"Entiende la tensión.","Live scores, accountable model reads, and the market context behind every prediction.":"Resultados en vivo, análisis verificables del modelo y el contexto del mercado detrás de cada predicción.","Still in development":"Todavía en desarrollo","You’re using an early version of Matchday. Some data and features may change as we improve it with real feedback.":"Estás usando una versión inicial de Matchday. Algunos datos y funciones pueden cambiar mientras mejoramos con opiniones reales.","Enter Matchday":"Entrar a Matchday","Analytics only · no tips · no ads":"Solo análisis · sin pronósticos de apuesta · sin anuncios","Model vs market":"Modelo frente al mercado","Probability, not certainty.":"Probabilidad, no certeza.","Locked in public":"Registrado públicamente","Picks never rewritten.":"Las predicciones no se reescriben.","Every sport":"Todos los deportes","One calm live terminal.":"Un solo panel en vivo y ordenado.",
"Personalize your terminal.":"Personaliza tu panel.","These settings save locally in this browser/app window.":"Estos ajustes se guardan localmente en este navegador.","Accent color":"Color de acento","Language":"Idioma","Card density":"Densidad de tarjetas","Panel style":"Estilo del panel","Default tab":"Pestaña predeterminada","Refresh rate":"Frecuencia de actualización","Display":"Pantalla","Right insight panel":"Panel de análisis derecho","Match detail panels":"Paneles de detalle","Reset settings":"Restablecer ajustes","Check app status":"Comprobar estado","News cycle":"Ciclo de noticias","All sources":"Todas las fuentes","No headlines yet.":"Todavía no hay titulares.","In focus":"En foco","Latest from multiple sources":"Últimas noticias de varias fuentes","No match in focus yet.":"Todavía no hay partido destacado.","My team":"Mi equipo"
});
Object.assign(window.MD_I18N.fr,{
"Matches":"Matchs","Forecast":"Prévisions","Community":"Communauté","Team of Tournament":"Équipe du tournoi","Table":"Classement","Standings":"Classement","Rankings":"Classements","Conferences":"Conférences","My team":"Mon équipe","No favorite selected":"Aucune équipe favorite","Your team moves to the front of matches, news, tables and the insight panel.":"Votre équipe passe en tête des matchs, actualités, classements et du panneau d’analyse.",
"Know the match.":"Comprenez le match.","See the tension.":"Voyez la tension.","Live scores, accountable model reads, and the market context behind every prediction.":"Scores en direct, analyses vérifiables du modèle et contexte du marché derrière chaque prévision.","Still in development":"Encore en développement","You’re using an early version of Matchday. Some data and features may change as we improve it with real feedback.":"Vous utilisez une première version de Matchday. Certaines données et fonctionnalités évolueront grâce aux retours réels.","Enter Matchday":"Entrer dans Matchday","Analytics only · no tips · no ads":"Analyse uniquement · aucun conseil · aucune publicité","Model vs market":"Modèle face au marché","Probability, not certainty.":"Une probabilité, pas une certitude.","Locked in public":"Verrouillé publiquement","Picks never rewritten.":"Les choix ne sont jamais réécrits.","Every sport":"Tous les sports","One calm live terminal.":"Un terminal en direct, clair et unique.",
"Personalize your terminal.":"Personnalisez votre terminal.","These settings save locally in this browser/app window.":"Ces réglages sont enregistrés localement dans ce navigateur.","Accent color":"Couleur d’accent","Language":"Langue","Card density":"Densité des cartes","Panel style":"Style des panneaux","Default tab":"Onglet par défaut","Refresh rate":"Fréquence d’actualisation","Display":"Affichage","Right insight panel":"Panneau d’analyse à droite","Match detail panels":"Détails des matchs","Reset settings":"Réinitialiser","Check app status":"Vérifier l’état","News cycle":"Fil d’actualité","All sources":"Toutes les sources","No headlines yet.":"Aucun titre pour le moment.","Latest from multiple sources":"Dernières nouvelles de plusieurs sources","No match in focus yet.":"Aucun match à la une pour le moment."
});
Object.assign(window.MD_I18N.de,{
"Matches":"Spiele","Forecast":"Prognose","Community":"Community","Team of Tournament":"Team des Turniers","Table":"Tabelle","Standings":"Tabelle","Rankings":"Rangliste","Conferences":"Conferences","My team":"Mein Team","No favorite selected":"Kein Lieblingsteam ausgewählt","Your team moves to the front of matches, news, tables and the insight panel.":"Dein Team wird bei Spielen, News, Tabellen und im Analysebereich nach vorn gestellt.",
"Know the match.":"Verstehe das Spiel.","See the tension.":"Spüre die Spannung.","Live scores, accountable model reads, and the market context behind every prediction.":"Live-Ergebnisse, überprüfbare Modellanalysen und der Marktkontext hinter jeder Prognose.","Still in development":"Noch in Entwicklung","You’re using an early version of Matchday. Some data and features may change as we improve it with real feedback.":"Du nutzt eine frühe Version von Matchday. Daten und Funktionen können sich durch echtes Feedback noch ändern.","Enter Matchday":"Matchday öffnen","Analytics only · no tips · no ads":"Nur Analyse · keine Tipps · keine Werbung","Model vs market":"Modell gegen Markt","Probability, not certainty.":"Wahrscheinlichkeit, keine Gewissheit.","Locked in public":"Öffentlich festgehalten","Picks never rewritten.":"Prognosen werden nie umgeschrieben.","Every sport":"Jede Sportart","One calm live terminal.":"Ein ruhiges Live-Terminal.",
"Personalize your terminal.":"Personalisiere dein Terminal.","These settings save locally in this browser/app window.":"Diese Einstellungen werden lokal in diesem Browser gespeichert.","Accent color":"Akzentfarbe","Language":"Sprache","Card density":"Kartendichte","Panel style":"Panelstil","Default tab":"Standard-Tab","Refresh rate":"Aktualisierungsrate","Display":"Anzeige","Right insight panel":"Rechtes Analysepanel","Match detail panels":"Spieldetails","Reset settings":"Einstellungen zurücksetzen","Check app status":"App-Status prüfen","News cycle":"News-Zyklus","All sources":"Alle Quellen","No headlines yet.":"Noch keine Meldungen.","Latest from multiple sources":"Aktuelles aus mehreren Quellen","No match in focus yet.":"Noch kein Spiel im Fokus."
});
Object.assign(window.MD_I18N.pt,{
"Matches":"Jogos","Forecast":"Previsão","Community":"Comunidade","Team of Tournament":"Seleção do torneio","Table":"Tabela","Standings":"Classificação","Rankings":"Ranking","Conferences":"Conferências","My team":"Meu time","No favorite selected":"Nenhum time favorito","Your team moves to the front of matches, news, tables and the insight panel.":"Seu time aparece primeiro em jogos, notícias, tabelas e no painel de análise.",
"Know the match.":"Conheça o jogo.","See the tension.":"Veja a tensão.","Live scores, accountable model reads, and the market context behind every prediction.":"Placar ao vivo, análises verificáveis do modelo e o contexto do mercado por trás de cada previsão.","Still in development":"Ainda em desenvolvimento","You’re using an early version of Matchday. Some data and features may change as we improve it with real feedback.":"Você está usando uma versão inicial do Matchday. Dados e recursos podem mudar com base em feedback real.","Enter Matchday":"Entrar no Matchday","Analytics only · no tips · no ads":"Somente análise · sem palpites · sem anúncios","Model vs market":"Modelo contra mercado","Probability, not certainty.":"Probabilidade, não certeza.","Locked in public":"Registrado publicamente","Picks never rewritten.":"As previsões nunca são reescritas.","Every sport":"Todos os esportes","One calm live terminal.":"Um painel ao vivo, simples e tranquilo.",
"Personalize your terminal.":"Personalize seu painel.","These settings save locally in this browser/app window.":"Estas configurações ficam salvas localmente neste navegador.","Accent color":"Cor de destaque","Language":"Idioma","Card density":"Densidade dos cartões","Panel style":"Estilo do painel","Default tab":"Aba padrão","Refresh rate":"Taxa de atualização","Display":"Exibição","Right insight panel":"Painel de análise à direita","Match detail panels":"Detalhes das partidas","Reset settings":"Redefinir configurações","Check app status":"Verificar status","News cycle":"Ciclo de notícias","All sources":"Todas as fontes","No headlines yet.":"Ainda não há manchetes.","Latest from multiple sources":"Últimas de várias fontes","No match in focus yet.":"Nenhuma partida em destaque."
});
Object.assign(window.MD_I18N.ru,{
"Matches":"Матчи","Forecast":"Прогноз","Community":"Сообщество","Team of Tournament":"Сборная турнира","Table":"Таблица","Standings":"Таблица","Rankings":"Рейтинг","Conferences":"Конференции","My team":"Моя команда","No favorite selected":"Любимая команда не выбрана","Your team moves to the front of matches, news, tables and the insight panel.":"Ваша команда будет показана первой в матчах, новостях, таблицах и панели анализа.",
"Know the match.":"Знай матч.","See the tension.":"Чувствуй интригу.","Live scores, accountable model reads, and the market context behind every prediction.":"Счёт в реальном времени, проверяемая аналитика модели и рыночный контекст каждого прогноза.","Still in development":"Проект ещё разрабатывается","You’re using an early version of Matchday. Some data and features may change as we improve it with real feedback.":"Вы используете раннюю версию Matchday. Данные и функции могут меняться благодаря отзывам пользователей.","Enter Matchday":"Открыть Matchday","Analytics only · no tips · no ads":"Только аналитика · без советов · без рекламы","Model vs market":"Модель против рынка","Probability, not certainty.":"Вероятность, а не уверенность.","Locked in public":"Публично зафиксировано","Picks never rewritten.":"Прогнозы не переписываются.","Every sport":"Все виды спорта","One calm live terminal.":"Единый спокойный live-терминал.",
"Personalize your terminal.":"Настройте терминал.","These settings save locally in this browser/app window.":"Настройки сохраняются локально в этом браузере.","Accent color":"Цвет акцента","Language":"Язык","Card density":"Плотность карточек","Panel style":"Стиль панелей","Default tab":"Вкладка по умолчанию","Refresh rate":"Частота обновления","Display":"Отображение","Right insight panel":"Правая панель анализа","Match detail panels":"Детали матчей","Reset settings":"Сбросить настройки","Check app status":"Проверить статус","News cycle":"Лента новостей","All sources":"Все источники","No headlines yet.":"Новостей пока нет.","Latest from multiple sources":"Последнее из разных источников","No match in focus yet.":"Матча в фокусе пока нет."
});

Object.assign(window.MD_I18N.es,{
"Matchday orange":"Naranja Matchday","Electric blue":"Azul eléctrico","Pitch green":"Verde césped","Live red":"Rojo en vivo","Night purple":"Morado nocturno","Compact":"Compacta","Normal":"Normal","Spacious":"Espaciosa","Soft glass":"Cristal suave","Flat dark":"Oscuro plano",
"Changes highlights, buttons and the brand dot.":"Cambia los destacados, los botones y el punto de la marca.","Translates the interface. Match data stays as provided by sources.":"Traduce la interfaz. Los datos deportivos se mantienen tal como los entregan las fuentes.","Compact fits more matches; spacious feels more premium.":"Compacta muestra más partidos; espaciosa ofrece una presentación más amplia.","Flat mode is lighter on older laptops.":"El modo plano consume menos recursos en equipos antiguos.","Selected when the page starts.":"Se abre al iniciar la página."
});
Object.assign(window.MD_I18N.fr,{
"Matchday orange":"Orange Matchday","Electric blue":"Bleu électrique","Pitch green":"Vert pelouse","Live red":"Rouge direct","Night purple":"Violet nocturne","Compact":"Compacte","Normal":"Normale","Spacious":"Aérée","Soft glass":"Verre doux","Flat dark":"Sombre uni",
"Changes highlights, buttons and the brand dot.":"Modifie les éléments mis en avant, les boutons et le point de la marque.","Translates the interface. Match data stays as provided by sources.":"Traduit l’interface. Les données sportives restent telles que fournies par les sources.","Compact fits more matches; spacious feels more premium.":"Le mode compact affiche plus de matchs ; le mode aéré offre plus d’espace.","Flat mode is lighter on older laptops.":"Le mode uni est plus léger sur les anciens ordinateurs.","Selected when the page starts.":"S’ouvre au démarrage de la page."
});
Object.assign(window.MD_I18N.de,{
"Matchday orange":"Matchday-Orange","Electric blue":"Elektrisches Blau","Pitch green":"Rasengrün","Live red":"Live-Rot","Night purple":"Nachtviolett","Compact":"Kompakt","Normal":"Normal","Spacious":"Großzügig","Soft glass":"Sanftes Glas","Flat dark":"Flach dunkel",
"Changes highlights, buttons and the brand dot.":"Ändert Hervorhebungen, Schaltflächen und den Markenpunkt.","Translates the interface. Match data stays as provided by sources.":"Übersetzt die Oberfläche. Sportdaten bleiben so, wie sie von den Quellen geliefert werden.","Compact fits more matches; spacious feels more premium.":"Kompakt zeigt mehr Spiele; großzügig bietet mehr Raum.","Flat mode is lighter on older laptops.":"Der flache Modus schont ältere Geräte.","Selected when the page starts.":"Wird beim Start der Seite geöffnet."
});
Object.assign(window.MD_I18N.pt,{
"Matchday orange":"Laranja Matchday","Electric blue":"Azul elétrico","Pitch green":"Verde gramado","Live red":"Vermelho ao vivo","Night purple":"Roxo noturno","Compact":"Compacta","Normal":"Normal","Spacious":"Espaçosa","Soft glass":"Vidro suave","Flat dark":"Escuro plano",
"Changes highlights, buttons and the brand dot.":"Altera destaques, botões e o ponto da marca.","Translates the interface. Match data stays as provided by sources.":"Traduz a interface. Os dados esportivos permanecem como são fornecidos pelas fontes.","Compact fits more matches; spacious feels more premium.":"Compacta mostra mais jogos; espaçosa oferece mais respiro.","Flat mode is lighter on older laptops.":"O modo plano é mais leve em computadores antigos.","Selected when the page starts.":"É aberta ao iniciar a página."
});
Object.assign(window.MD_I18N.ru,{
"Matchday orange":"Оранжевый Matchday","Electric blue":"Электрический синий","Pitch green":"Зелёный газон","Live red":"Красный live","Night purple":"Ночной фиолетовый","Compact":"Компактно","Normal":"Обычно","Spacious":"Просторно","Soft glass":"Мягкое стекло","Flat dark":"Плоская тёмная",
"Changes highlights, buttons and the brand dot.":"Меняет акценты, кнопки и точку бренда.","Translates the interface. Match data stays as provided by sources.":"Переводит интерфейс. Спортивные данные остаются в виде, предоставленном источниками.","Compact fits more matches; spacious feels more premium.":"Компактный режим показывает больше матчей, просторный даёт больше воздуха.","Flat mode is lighter on older laptops.":"Плоский режим меньше нагружает старые компьютеры.","Selected when the page starts.":"Открывается при запуске страницы."
});

// Shared dynamic dashboard copy. These are intentionally limited to Matchday's
// own UI: team names, source headlines, and provider descriptions remain intact.
const MD_DYNAMIC_UI = {
es:{"No live matches":"No hay partidos en vivo","No upcoming fixtures":"No hay próximos partidos","No live or upcoming matches to show.":"No hay partidos en vivo ni próximos para mostrar.","No headlines yet.":"Todavía no hay titulares.","No match in focus yet.":"Todavía no hay partido destacado.","No group data found yet.":"Todavía no hay datos de grupo.","No model picks yet.":"Todavía no hay predicciones del modelo.","No market to compare against":"No hay mercado para comparar","No 1X2 market odds yet.":"Aún no hay cuotas de mercado 1X2.","No data":"Sin datos","No data files yet":"Aún no hay archivos de datos","Updated ":"Actualizado ","Next ·":"Siguiente ·","Showing ":"Mostrando ","Load ":"Cargar "," more":" más","fixtures":"partidos","headlines":"titulares","detected sources":"fuentes detectadas","national poll":"clasificación nacional","raw season records":"registros de temporada","Regular Season":"Temporada regular","Postseason":"Postemporada","Week ":"Semana ","Completed archive":"Archivo finalizado","Active pick board":"Panel de predicciones activas","Quick reads":"Lecturas rápidas","Actionable":"Accionable","High confidence":"Alta confianza","With market":"Con mercado","All active":"Todos activos","Archive":"Archivo","Live stats loading…":"Cargando estadísticas en vivo…","Box score unavailable":"Estadísticas no disponibles","Box score not yet available":"Las estadísticas aún no están disponibles","Stats appear once the match kicks off.":"Las estadísticas aparecen cuando comienza el partido.","Close":"Cerrar","Home":"Local","Away":"Visitante","Fixture":"Partido","Data file not loaded.":"Archivo de datos no cargado."},
fr:{"No live matches":"Aucun match en direct","No upcoming fixtures":"Aucun match à venir","No live or upcoming matches to show.":"Aucun match en direct ou à venir à afficher.","No headlines yet.":"Aucun titre pour le moment.","No match in focus yet.":"Aucun match à la une pour le moment.","No group data found yet.":"Aucune donnée de groupe pour le moment.","No model picks yet.":"Aucun choix du modèle pour le moment.","No market to compare against":"Aucun marché à comparer","No 1X2 market odds yet.":"Aucune cote 1X2 disponible pour le moment.","No data":"Aucune donnée","No data files yet":"Aucun fichier de données pour le moment","Updated ":"Mis à jour ","Next ·":"Suivant ·","Showing ":"Affichage de ","Load ":"Charger "," more":" de plus","fixtures":"matchs","headlines":"titres","detected sources":"sources détectées","national poll":"classement national","raw season records":"bilans de saison","Regular Season":"Saison régulière","Postseason":"Après-saison","Week ":"Semaine ","Completed archive":"Archives terminées","Active pick board":"Tableau des choix actifs","Quick reads":"Lectures rapides","Actionable":"À suivre","High confidence":"Forte confiance","With market":"Avec marché","All active":"Tous actifs","Archive":"Archives","Live stats loading…":"Chargement des statistiques en direct…","Box score unavailable":"Feuille de match indisponible","Box score not yet available":"Feuille de match pas encore disponible","Stats appear once the match kicks off.":"Les statistiques apparaissent au coup d’envoi.","Close":"Fermer","Home":"Domicile","Away":"Extérieur","Fixture":"Match","Data file not loaded.":"Fichier de données non chargé."},
de:{"No live matches":"Keine Live-Spiele","No upcoming fixtures":"Keine anstehenden Spiele","No live or upcoming matches to show.":"Keine Live- oder anstehenden Spiele zum Anzeigen.","No headlines yet.":"Noch keine Meldungen.","No match in focus yet.":"Noch kein Spiel im Fokus.","No group data found yet.":"Noch keine Gruppendaten vorhanden.","No model picks yet.":"Noch keine Modelltipps.","No market to compare against":"Kein Markt zum Vergleichen","No 1X2 market odds yet.":"Noch keine 1X2-Marktquoten.","No data":"Keine Daten","No data files yet":"Noch keine Datendateien","Updated ":"Aktualisiert ","Next ·":"Nächstes ·","Showing ":"Anzeige ","Load ":"Laden "," more":" weitere","fixtures":"Spiele","headlines":"Meldungen","detected sources":"erkannte Quellen","national poll":"nationale Rangliste","raw season records":"Saisonbilanz","Regular Season":"Reguläre Saison","Postseason":"Postseason","Week ":"Woche ","Completed archive":"Abgeschlossenes Archiv","Active pick board":"Aktive Tipps","Quick reads":"Kurzanalysen","Actionable":"Relevant","High confidence":"Hohe Zuversicht","With market":"Mit Markt","All active":"Alle aktiven","Archive":"Archiv","Live stats loading…":"Live-Statistiken werden geladen…","Box score unavailable":"Spielstatistik nicht verfügbar","Box score not yet available":"Spielstatistik noch nicht verfügbar","Stats appear once the match kicks off.":"Statistiken erscheinen mit dem Anpfiff.","Close":"Schließen","Home":"Heim","Away":"Auswärts","Fixture":"Spiel","Data file not loaded.":"Datendatei nicht geladen."},
pt:{"No live matches":"Nenhum jogo ao vivo","No upcoming fixtures":"Nenhum jogo próximo","No live or upcoming matches to show.":"Nenhum jogo ao vivo ou próximo para mostrar.","No headlines yet.":"Ainda não há manchetes.","No match in focus yet.":"Nenhuma partida em destaque.","No group data found yet.":"Ainda não há dados de grupos.","No model picks yet.":"Ainda não há escolhas do modelo.","No market to compare against":"Nenhum mercado para comparar","No 1X2 market odds yet.":"Ainda não há odds de mercado 1X2.","No data":"Sem dados","No data files yet":"Ainda não há arquivos de dados","Updated ":"Atualizado ","Next ·":"Próximo ·","Showing ":"Mostrando ","Load ":"Carregar "," more":" mais","fixtures":"jogos","headlines":"manchetes","detected sources":"fontes detectadas","national poll":"ranking nacional","raw season records":"registros da temporada","Regular Season":"Temporada regular","Postseason":"Pós-temporada","Week ":"Semana ","Completed archive":"Arquivo concluído","Active pick board":"Painel de escolhas ativas","Quick reads":"Leituras rápidas","Actionable":"Em jogo","High confidence":"Alta confiança","With market":"Com mercado","All active":"Todos ativos","Archive":"Arquivo","Live stats loading…":"Carregando estatísticas ao vivo…","Box score unavailable":"Estatísticas indisponíveis","Box score not yet available":"Estatísticas ainda não disponíveis","Stats appear once the match kicks off.":"As estatísticas aparecem quando a partida começa.","Close":"Fechar","Home":"Casa","Away":"Fora","Fixture":"Partida","Data file not loaded.":"Arquivo de dados não carregado."},
ru:{"No live matches":"Нет матчей в прямом эфире","No upcoming fixtures":"Нет ближайших матчей","No live or upcoming matches to show.":"Нет матчей в эфире или ближайших матчей для показа.","No headlines yet.":"Новостей пока нет.","No match in focus yet.":"Матча в фокусе пока нет.","No group data found yet.":"Данных по группам пока нет.","No model picks yet.":"Прогнозов модели пока нет.","No market to compare against":"Нет рынка для сравнения","No 1X2 market odds yet.":"Коэффициенты рынка 1X2 пока недоступны.","No data":"Нет данных","No data files yet":"Файлов данных пока нет","Updated ":"Обновлено ","Next ·":"Далее ·","Showing ":"Показано ","Load ":"Загрузить "," more":" ещё","fixtures":"матчей","headlines":"заголовков","detected sources":"источников","national poll":"национальный рейтинг","raw season records":"результаты сезона","Regular Season":"Регулярный сезон","Postseason":"Постсезон","Week ":"Неделя ","Completed archive":"Завершённый архив","Active pick board":"Активные прогнозы","Quick reads":"Краткие выводы","Actionable":"Актуально","High confidence":"Высокая уверенность","With market":"С рынком","All active":"Все активные","Archive":"Архив","Live stats loading…":"Загружается статистика в реальном времени…","Box score unavailable":"Статистика матча недоступна","Box score not yet available":"Статистика матча пока недоступна","Stats appear once the match kicks off.":"Статистика появится после начала матча.","Close":"Закрыть","Home":"Хозяева","Away":"Гости","Fixture":"Матч","Data file not loaded.":"Файл данных не загружен."}
};
Object.entries(MD_DYNAMIC_UI).forEach(([lang,strings])=>Object.assign(window.MD_I18N[lang],strings));
