// GENERATED by social_export.py -- do not edit by hand.
// Every number here comes from betbetter_picks.json, filtered to the
// current playing week. Regenerate with: python social_export.py --js
window.MATCHDAY_SOCIAL = {
  "week": "WEEK OF SEP 08",
  "season": "2026 SEASON",
  "published": "2026-09-07",
  "generated_at": "2026-09-08T17:01:33Z",
  "logos": {
    "Indiana Hoosiers": "logos/indiana.png",
    "INDIANA": "logos/indiana.png",
    "Indiana": "logos/indiana.png",
    "Ohio State Buckeyes": "logos/ohioState.png",
    "OHIO STATE": "logos/ohioState.png",
    "Ohio State": "logos/ohioState.png",
    "Notre Dame Fighting Irish": "logos/notreDame.png",
    "NOTRE DAME": "logos/notreDame.png",
    "Notre Dame": "logos/notreDame.png",
    "Oregon Ducks": "logos/oregon.png",
    "OREGON": "logos/oregon.png",
    "Oregon": "logos/oregon.png",
    "Miami Hurricanes": "logos/miami.png",
    "MIAMI": "logos/miami.png",
    "Miami": "logos/miami.png",
    "Texas Longhorns": "logos/texas.png",
    "TEXAS": "logos/texas.png",
    "Texas": "logos/texas.png",
    "Georgia Bulldogs": "logos/georgia.png",
    "GEORGIA": "logos/georgia.png",
    "Georgia": "logos/georgia.png",
    "Utah Utes": "logos/utah.png",
    "UTAH": "logos/utah.png",
    "Utah": "logos/utah.png",
    "Ole Miss Rebels": "logos/oleMiss.png",
    "OLE MISS": "logos/oleMiss.png",
    "Ole Miss": "logos/oleMiss.png",
    "Texas Tech Red Raiders": "logos/texas.png",
    "TEXAS TECH": "logos/texasTech.png",
    "Texas Tech": "logos/texasTech.png",
    "Alabama Crimson Tide": "logos/alabama.png",
    "ALABAMA": "logos/alabama.png",
    "Alabama": "logos/alabama.png",
    "Penn State Nittany Lions": "logos/pennState.png",
    "PENN STATE": "logos/pennState.png",
    "Penn State": "logos/pennState.png",
    "Texas A&M Aggies": "logos/texas.png",
    "TEXAS A&M": "logos/texasAM.png",
    "Texas A&M": "logos/texasAM.png",
    "USC Trojans": "logos/usc.png",
    "USC": "logos/usc.png",
    "Iowa Hawkeyes": "logos/iowa.png",
    "IOWA": "logos/iowa.png",
    "Iowa": "logos/iowa.png",
    "Oklahoma Sooners": "logos/oklahoma.png",
    "OKLAHOMA": "logos/oklahoma.png",
    "Oklahoma": "logos/oklahoma.png",
    "Washington Huskies": "logos/washington.png",
    "WASHINGTON": "logos/washington.png",
    "Washington": "logos/washington.png",
    "Tennessee Volunteers": "logos/tennessee.png",
    "TENNESSEE": "logos/tennessee.png",
    "Tennessee": "logos/tennessee.png",
    "BYU Cougars": "logos/byu.png",
    "BYU": "logos/byu.png",
    "SMU Mustangs": "logos/smu.png",
    "SMU": "logos/smu.png",
    "Michigan Wolverines": "logos/michigan.png",
    "MICHIGAN": "logos/michigan.png",
    "Michigan": "logos/michigan.png",
    "LSU Tigers": "logos/lsu.png",
    "LSU": "logos/lsu.png",
    "Louisville Cardinals": "logos/louisville.png",
    "LOUISVILLE": "logos/louisville.png",
    "Louisville": "logos/louisville.png",
    "Vanderbilt Commodores": "logos/vanderbilt.png",
    "VANDERBILT": "logos/vanderbilt.png",
    "Vanderbilt": "logos/vanderbilt.png",
    "Missouri Tigers": "logos/missouri.png",
    "MISSOURI": "logos/missouri.png",
    "Missouri": "logos/missouri.png",
    "Oklahoma State Cowboys": "logos/oklahoma.png",
    "OKLAHOMA STATE": "logos/oklahoma.png",
    "Oklahoma State": "logos/oklahoma.png"
  },
  "top25": [
    [
      "Indiana Hoosiers",
      31.35
    ],
    [
      "Ohio State Buckeyes",
      30.87
    ],
    [
      "Notre Dame Fighting Irish",
      29.05
    ],
    [
      "Oregon Ducks",
      25.65
    ],
    [
      "Miami Hurricanes",
      25.01
    ],
    [
      "Texas Longhorns",
      23.82
    ],
    [
      "Georgia Bulldogs",
      23.55
    ],
    [
      "Utah Utes",
      23.25
    ],
    [
      "Ole Miss Rebels",
      23.22
    ],
    [
      "Texas Tech Red Raiders",
      23.0
    ],
    [
      "Alabama Crimson Tide",
      22.37
    ],
    [
      "Penn State Nittany Lions",
      22.2
    ],
    [
      "Texas A&M Aggies",
      21.77
    ],
    [
      "USC Trojans",
      21.08
    ],
    [
      "Iowa Hawkeyes",
      20.28
    ],
    [
      "Oklahoma Sooners",
      20.07
    ],
    [
      "Washington Huskies",
      19.33
    ],
    [
      "Tennessee Volunteers",
      19.04
    ],
    [
      "BYU Cougars",
      18.51
    ],
    [
      "SMU Mustangs",
      18.32
    ],
    [
      "Michigan Wolverines",
      17.99
    ],
    [
      "LSU Tigers",
      17.11
    ],
    [
      "Louisville Cardinals",
      16.87
    ],
    [
      "Vanderbilt Commodores",
      16.76
    ],
    [
      "Missouri Tigers",
      16.64
    ]
  ],
  "upset": {
    "eyebrow": "MODEL UPSET WATCH",
    "underdog": "BUFFALO BULLS",
    "favorite": "FLORIDA INTERNATIONAL",
    "kickoff": "SAT · 6:00 PM ET",
    "modelPct": 56.1,
    "marketPct": 22.9,
    "note": "The model gives Buffalo Bulls 56.1% where the market gives 22.9%."
  },
  "slate": [
    {
      "rank": 1,
      "away": "OHIO STATE",
      "home": "TEXAS",
      "time": "SAT · 7:30 PM ET",
      "hook": "#2 vs #6"
    },
    {
      "rank": 2,
      "away": "OREGON",
      "home": "OKLAHOMA STATE",
      "time": "SAT · 12:00 PM ET",
      "hook": "RANKED #4 ON THE ROAD"
    },
    {
      "rank": 3,
      "away": "OKLAHOMA",
      "home": "MICHIGAN",
      "time": "SAT · 12:00 PM ET",
      "hook": "#16 vs #21"
    },
    {
      "rank": 4,
      "away": "RICE",
      "home": "NOTRE DAME",
      "time": "SAT · 3:30 PM ET",
      "hook": "RANKED #3 AT HOME"
    },
    {
      "rank": 5,
      "away": "ARKANSAS",
      "home": "UTAH",
      "time": "SAT · 12:00 PM ET",
      "hook": "RANKED #8 AT HOME"
    }
  ]
};
