// GENERATED by social_export.py -- do not edit by hand.
// Every number here comes from betbetter_picks.json, filtered to the
// current playing week. Regenerate with: python social_export.py --js
window.MATCHDAY_SOCIAL = {
  "week": "WEEK OF SEP 15",
  "season": "2026 SEASON",
  "published": "2026-09-13",
  "generated_at": "2026-09-15T17:26:52Z",
  "logos": {
    "Indiana Hoosiers": "logos/indiana.png",
    "INDIANA": "logos/indiana.png",
    "Indiana": "logos/indiana.png",
    "Ohio State Buckeyes": "logos/ohioState.png",
    "OHIO STATE": "logos/ohioState.png",
    "Ohio State": "logos/ohioState.png",
    "Notre Dame Fighting Irish": "logos/notreDame.png",
    "NOTRE DAME": "logos/notreDame.png",
    "Notre Dame": "logos/notreDame.png",
    "Miami Hurricanes": "logos/miami.png",
    "MIAMI": "logos/miami.png",
    "Miami": "logos/miami.png",
    "Georgia Bulldogs": "logos/georgia.png",
    "GEORGIA": "logos/georgia.png",
    "Georgia": "logos/georgia.png",
    "Utah Utes": "logos/utah.png",
    "UTAH": "logos/utah.png",
    "Utah": "logos/utah.png",
    "Texas Longhorns": "logos/texas.png",
    "TEXAS": "logos/texas.png",
    "Texas": "logos/texas.png",
    "Oregon Ducks": "logos/oregon.png",
    "OREGON": "logos/oregon.png",
    "Oregon": "logos/oregon.png",
    "Alabama Crimson Tide": "logos/alabama.png",
    "ALABAMA": "logos/alabama.png",
    "Alabama": "logos/alabama.png",
    "Ole Miss Rebels": "logos/oleMiss.png",
    "OLE MISS": "logos/oleMiss.png",
    "Ole Miss": "logos/oleMiss.png",
    "Texas A&M Aggies": "logos/texas.png",
    "TEXAS A&M": "logos/texasAM.png",
    "Texas A&M": "logos/texasAM.png",
    "Texas Tech Red Raiders": "logos/texas.png",
    "TEXAS TECH": "logos/texasTech.png",
    "Texas Tech": "logos/texasTech.png",
    "Penn State Nittany Lions": "logos/pennState.png",
    "PENN STATE": "logos/pennState.png",
    "Penn State": "logos/pennState.png",
    "USC Trojans": "logos/usc.png",
    "USC": "logos/usc.png",
    "Tennessee Volunteers": "logos/tennessee.png",
    "TENNESSEE": "logos/tennessee.png",
    "Tennessee": "logos/tennessee.png",
    "Oklahoma Sooners": "logos/oklahoma.png",
    "OKLAHOMA": "logos/oklahoma.png",
    "Oklahoma": "logos/oklahoma.png",
    "Iowa Hawkeyes": "logos/iowa.png",
    "IOWA": "logos/iowa.png",
    "Iowa": "logos/iowa.png",
    "SMU Mustangs": "logos/smu.png",
    "SMU": "logos/smu.png",
    "BYU Cougars": "logos/byu.png",
    "BYU": "logos/byu.png",
    "LSU Tigers": "logos/lsu.png",
    "LSU": "logos/lsu.png",
    "Michigan Wolverines": "logos/michigan.png",
    "MICHIGAN": "logos/michigan.png",
    "Michigan": "logos/michigan.png",
    "Washington Huskies": "logos/washington.png",
    "WASHINGTON": "logos/washington.png",
    "Washington": "logos/washington.png",
    "Missouri Tigers": "logos/missouri.png",
    "MISSOURI": "logos/missouri.png",
    "Missouri": "logos/missouri.png",
    "Louisville Cardinals": "logos/louisville.png",
    "LOUISVILLE": "logos/louisville.png",
    "Louisville": "logos/louisville.png",
    "Michigan State Spartans": "logos/michigan.png",
    "MICHIGAN STATE": "logos/michigan.png",
    "Michigan State": "logos/michigan.png"
  },
  "top25": [
    [
      "Indiana Hoosiers",
      31.43
    ],
    [
      "Ohio State Buckeyes",
      30.51
    ],
    [
      "Notre Dame Fighting Irish",
      30.44
    ],
    [
      "Miami Hurricanes",
      26.49
    ],
    [
      "Georgia Bulldogs",
      25.75
    ],
    [
      "Utah Utes",
      24.66
    ],
    [
      "Texas Longhorns",
      24.3
    ],
    [
      "Oregon Ducks",
      24.01
    ],
    [
      "Alabama Crimson Tide",
      23.78
    ],
    [
      "Ole Miss Rebels",
      23.62
    ],
    [
      "Texas A&M Aggies",
      23.32
    ],
    [
      "Texas Tech Red Raiders",
      22.88
    ],
    [
      "Penn State Nittany Lions",
      22.3
    ],
    [
      "USC Trojans",
      21.38
    ],
    [
      "Tennessee Volunteers",
      20.34
    ],
    [
      "Oklahoma Sooners",
      20.24
    ],
    [
      "Iowa Hawkeyes",
      19.89
    ],
    [
      "SMU Mustangs",
      18.96
    ],
    [
      "BYU Cougars",
      18.76
    ],
    [
      "LSU Tigers",
      18.67
    ],
    [
      "Michigan Wolverines",
      18.58
    ],
    [
      "Washington Huskies",
      18.3
    ],
    [
      "Missouri Tigers",
      17.84
    ],
    [
      "Louisville Cardinals",
      17.62
    ],
    [
      "Kansas State Wildcats",
      17.31
    ]
  ],
  "upset": {
    "eyebrow": "MODEL UPSET WATCH",
    "underdog": "MISSISSIPPI STATE",
    "favorite": "SOUTH CAROLINA",
    "kickoff": "SAT · 4:15 PM ET",
    "modelPct": 44.2,
    "marketPct": 28.3,
    "note": "The model gives Mississippi State 44.2% where the market gives 28.3%."
  },
  "slate": [
    {
      "rank": 1,
      "away": "LSU",
      "home": "OLE MISS",
      "time": "SAT · 7:30 PM ET",
      "hook": "#20 vs #10"
    },
    {
      "rank": 2,
      "away": "MICHIGAN STATE",
      "home": "NOTRE DAME",
      "time": "SAT · 7:30 PM ET",
      "hook": "RANKED #3 AT HOME"
    },
    {
      "rank": 3,
      "away": "MIAMI",
      "home": "WAKE FOREST",
      "time": "FRI · 7:30 PM ET",
      "hook": "RANKED #4 ON THE ROAD"
    },
    {
      "rank": 4,
      "away": "GEORGIA",
      "home": "ARKANSAS",
      "time": "SAT · 12:00 PM ET",
      "hook": "RANKED #5 ON THE ROAD"
    },
    {
      "rank": 5,
      "away": "WESTERN KENTUCKY",
      "home": "INDIANA",
      "time": "SAT · 4:00 PM ET",
      "hook": "RANKED #1 AT HOME"
    }
  ]
};
